create-test:
    clickhouse-client --query "`cat test-beryl.sql`"
    clickhouse-client --query "`cat test-beryl-insert.sql`"

drop-test:
    clickhouse-client --query 'drop table test_beryl'

# match will have better parsing so that `match` keyword is not needed in query
test:
    curl "127.0.0.1:9999/api/stores?number_employees=gt.500"
    curl "127.0.0.1:9999/api/stores?name=match.Store1"
    curl "127.0.0.1:9999/api/stores?stocks_product=in_array.NIKE,~FILO"
